### PR TITLE
Additional Changes to External Docs for Phone PIN

### PR DESCRIPTION
**Pull request by dnya3698**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 30 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-53da2a53f/docs/cloud-identity/v2/). valid for 14 days

**Comment by edwardjrp** [comment]
build me

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 34 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d510ca585/docs/cloud-identity/v2/). valid for 14 days

**Pull request merged**
