### PR TITLE
Change phone PIN to Support PIN and fix phone-pin-operations.rst

### PR DESCRIPTION
**Pull request by cyrichardson**
to have sections with links to different types of operations

### CODE REVIEW

**Comment by cyrichardson** [comment]
@dnya3698 This doesn't add a 3rd level in the left navigation (which is not Rackspace style for other API guides) but it does add bold titles with links under them to the different types of things you can do for Support PINs and then provides a link under them. 

Wait for the staging publishing to build, which can take a while, and I will send you a link to check this update out.

**Comment by rackernexus** [comment]
Build 36 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e4ccdc64a/docs/cloud-identity/v2/). valid for 14 days

**Comment by cyrichardson** [comment]
https://developer-revs.staging.deconst.org/build-e4ccdc64a/docs/cloud-identity/v2/api-reference/phone-pin-operations/

^^ @dnya3698 Please check out the link above. See if this meet your needs given our constraints on style.

**Comment by rackernexus** [comment]
Build 37 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-64c17ab91/docs/cloud-identity/v2/). valid for 14 days

**Comment by cyrichardson** [comment]
@dnya3698 New link to check https://developer-revs.staging.deconst.org/build-e4ccdc64a/docs/cloud-identity/v2/api-reference/phone-pin-operations/

Had to change width: auto for tables... our build does not support it. Have to use numbers.

**Comment by cyrichardson** [comment]
Merging at @dnya3698 request.

**Pull request merged**
